main: network.aeternum.mythicmeteors.MythicMeteors
name: MythicMeteors
version: 1.1
author: BananaPuncher714
description: 
depend:
- "MythicMobs"
softdepend:
- "MVdWPlaceholderAPI"
- "PlaceholderAPI"
commands:
  mythicmeteor:
    description: Spawn your meteors and mobs
    
permissions:
  mythicmeteors.admin:
    default: op
  mythicmeteors.manage:
    default: op